name = "teenliwa"
account_id = "0b7dc087410628baa1f652ea0fb8bd57"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Static Assets for Cloudflare Workers
[assets]
directory = "./dist/client"
not_found_handling = "single-page-application"

[vars]
ENVIRONMENT = "production"
STORE_NAME = "teenliwa"
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin123456"

[[d1_databases]]
binding = "DB"
database_name = "teenliwa-db"
database_id = "93122110-3ccd-4de5-b607-48ee369e3e3a"

[[services]]
binding = "Todo_list"
service = "to-do-list-kv-template"
environment = "production"



