name = "teenliwa"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "dist/client"

[[d1_databases]]
binding = "DB1"
database_name = "db1"
database_id = "YOUR_CLOUDFLARE_D1_DATABASE_ID"
