name = "teenliwa"
account_id = "0b7dc087410628baa1f652ea0fb8bd57"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Static Assets for Cloudflare Workers
[assets]
directory = "./dist/client"
not_found_handling = "single-page-application"

[vars]
ENVIRONMENT = "production"
STORE_NAME = "teenliwa"

