import { execSync } from "child_process";
import fs from "fs";

// Read .env if exists
let envVars = { ...process.env };
try {
  if (fs.existsSync(".env")) {
    const envContent = fs.readFileSync(".env", "utf8");
    envContent.split("\n").forEach((line) => {
      const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
      if (match) {
        const key = match[1];
        let value = match[2] || "";
        if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);
        if (value.startsWith("'") && value.endsWith("'")) value = value.slice(1, -1);
        envVars[key] = value;
      }
    });
  }
} catch (e) {
  console.warn("Could not parse .env file:", e);
}

const token = envVars.CLOUDFLARE_API_TOKEN || envVars.VITE_CLOUDFLARE_API_TOKEN;
const accountId = envVars.CLOUDFLARE_ACCOUNT_ID || envVars.VITE_CLOUDFLARE_ACCOUNT_ID;
const apiKey = envVars.CLOUDFLARE_GLOBAL_API_KEY || envVars.VITE_CLOUDFLARE_GLOBAL_API_KEY;
const email = envVars.CLOUDFLARE_EMAIL || envVars.VITE_CLOUDFLARE_EMAIL;

console.log("Checking Cloudflare Deployment Credentials...");
console.log("- Token present:", !!token);
console.log("- Account ID present:", !!accountId);
console.log("- Global API Key present:", !!apiKey);
console.log("- Email present:", !!email);

const deployEnv = { ...envVars };

if (token) {
  deployEnv.CLOUDFLARE_API_TOKEN = token;
}
if (accountId) {
  deployEnv.CLOUDFLARE_ACCOUNT_ID = accountId;
}
if (apiKey) {
  deployEnv.CLOUDFLARE_API_KEY = apiKey;
}
if (email) {
  deployEnv.CLOUDFLARE_EMAIL = email;
}

function printDir(path) {
  try {
    const out = execSync(`ls -la ${path}`, { env: deployEnv, stdio: ["ignore", "pipe", "pipe"] }).toString();
    console.log(`\nContents of ${path}:\n${out}`);
  } catch (e) {
    console.log(`\nCannot list ${path}: ${e.message}`);
  }
}

try {
  console.log("\nBuilding project...");
  execSync("npm run build", { stdio: "inherit", env: deployEnv });

  // Verify build output
  printDir("dist");
  printDir("dist/client");

  if (!fs.existsSync("dist/client")) {
    console.error("\nError: Expected build output directory 'dist/client' not found.\nMake sure the build succeeded and Nitro output.publicDir is set to 'dist/client'.");
    process.exit(1);
  }

  console.log("\nDeploying to Cloudflare Pages...");
  // Deploy the client static output generated by Nitro (dist/client)
  try {
    execSync("npx wrangler pages deploy dist/client --project-name teenliwa", {
      stdio: "inherit",
      env: deployEnv,
    });
    console.log("\nDeployment completed successfully!");
  } catch (err) {
    console.error("\nwrangler deployment failed.");
    if (err.stdout) console.error("stdout:\n", err.stdout.toString());
    if (err.stderr) console.error("stderr:\n", err.stderr.toString());
    console.error("error message:", err.message);
    process.exit(1);
  }
} catch (error) {
  console.error("\nDeployment failed:", error.message);
  process.exit(1);
}
